[env]
SPRING_PROFILES_ACTIVE = "production"

[[services]]
name = "SafeSupport Backend"
buildCommand = "./mvnw clean package"
startCommand = "java -jar target/safesupport-0.0.1-SNAPSHOT.jar"

[services.variables]
SPRING_PROFILES_ACTIVE = "production"